version: '3.8'

services:
  web:
    build: .
    container_name: projet_rdv_web
    ports:
      - "8080:80"
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: projet_rdv_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gestion_rdv_medical
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
